[metadata]
  name = "das-benchmarks"
  author = "derrandz"

[global]
  plan = "celestia"
  case = "das-benchmarks"
  total_instances = 502
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false

[global.run.test_params]
  execution-time = "10"
  submit-times = "20"
  msg-size = "700000"
  validator = "1"
  bridge = "1"
  light = "500"
  block-height = "30"
  otel-collector-address = "178.128.163.171:4318"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "1"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "validator"

[[groups]]
  id = "bridges"
  builder = "docker:generic"
  [groups.resources]
    memory = "12Gi"
    cpu = "4"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "bridge"

[[groups]]
  id = "lights"
  builder = "docker:generic"
  [groups.resources]
    memory = "2Gi"
    cpu = "2000m"
  [groups.instances]
    count = 500
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "light"
