apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- service_api.yaml
- ingress_api.yaml
- ingress_rpc.yaml
- ingress_grpc.yaml

nameSuffix: -full

labels:
- pairs:
    app: consensus-full
    type: full
  includeSelectors: true
  includeTemplates: true

configMapGenerator:
- name: setup-full
  files:
  - setup.sh

patches:
- path: patches/statefulset.yaml
