[metadata]
  name = "blocksync-latest"
  author = "derrandz"

[global]
  plan = "celestia"
  case = "blocksync-latest"
  total_instances = 36
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false

# we define 1 validator that produces 8mb blocks
# the msg-size does not result in exactly 8mb
# because we are accounting for padding
[global.run.test_params]
  execution-time = "20"
  msg-size = "800000"
  validator = "1"
  bridge = "3"
  full = "32"
  block-height = "30"
  otel-collector-address = "178.128.163.171:4318"
  getter = "ipld"
  peers-limit = "3"
  bootstrapper = "true"
  interconnect-bridges = "true"
  multibootstrap = "true"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = "8Gi"
    cpu = "1"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "validator"

[[groups]]
  id = "bridges"
  builder = "docker:generic"
  [groups.resources]
    memory = "8Gi"
    cpu = "4"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "bridge"

[[groups]]
  id = "fulls"
  builder = "docker:generic"
  [groups.resources]
    memory = "8Gi"
    cpu = "4"
  [groups.instances]
    count = 32
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "full"
